name = "hyperx"
type = "javascript"

workers_dev = true
compatibility_date = "2024-02-26"
pages_build_output_dir = ".next/standalone"

[build]
command = "npm run build"

[env.production]
NODE_VERSION = "18.18.0"

[build.environment]
NODE_VERSION = "20.11.0"

[site]
bucket = ".next/static"
entry-point = "."

[build.upload]
format = "service-worker"
