name = "your-project-name"
type = "javascript"

workers_dev = true
compatibility_date = "2024-02-26"

[build]
command = "npm run build"
output_dir = ".next"

[env.production]
NODE_VERSION = "18.18.0"
