name = "hyperx"
compatibility_date = "2024-02-26"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"
output_dir = ".vercel/output/static"

[site]
bucket = ".vercel/output/static"
entry-point = "_worker.js"