name = "hyperx"
type = "javascript"

workers_dev = true
compatibility_date = "2024-02-26"

[build]
command = "npm run build"
output_dir = ".next"

[env.production]
NODE_VERSION = "18.18.0"

[build.environment]
NODE_VERSION = "20.11.0"

[site]
bucket = "out"
entry-point = "."

[build.upload]
format = "service-worker"
