name = "hyperx"
pages_build_output_dir = "out"

workers_dev = true
compatibility_date = "2024-02-26"

[build]
command = "npm run build"
output_directory = "out"

[env.production]
NODE_VERSION = "18.18.0"

[build.environment]
NODE_VERSION = "20.11.0"

[site]
bucket = ".next/static"
entry-point = "."

[build.upload]
format = "service-worker"
